os:
  - linux

language: php

php:
  - '7.2'

git:
  depth: false

before_script:
  - composer self-update
  - composer install --no-interaction

#script:
#  - vendor/bin/phpunit --coverage-text

deploy:
  provider: azure_web_apps
  verbose: true